config:
  # Config version
  version: 1

  # Config type
  type: discord-config-bot

bot:
  # Bot token from Discord Developer Portal
  token: "your-bot-token"

  # Activity settings
  # Text shown in Discord
  activity:
    text: "Discord Engine"

    # Type of activity: PLAYING, LISTENING, WATCHING, STREAMING, COMPETING
    type: "PLAYING"

    # URL for streaming (only used if type=STREAMING)
    url: ""

  # Resource sources
  sources:
    # Commands settings
    # Load mode: local, global, both
    commands:
      mode: "both"

      # Local command files
      local:
        - "commands.yml"

      # Global command files
      global:
        - "commands.yml"

    # Avatar settings
    # Load mode: local or global
    avatar:
      mode: "local"

      # Avatar file name
      file: "avatar-discordengine-nofon.png"

    # Language settings
    # Load mode: local or global
    lang:
      mode: "local"

      # Language file name
      file: "en_US.yml"
