config: # Please do not touch this section
  version: 1
  type: discord-config-bot

bot:
  # Bot token from Discord Developer Portal
  # IMPORTANT: Replace with your actual bot token
  token: "your-bot-token"

  # Bot activity configuration
  activity:
    # Activity text displayed in Discord
    text: "Discord Engine"
    # Activity type: PLAYING, LISTENING, WATCHING, STREAMING, COMPETING
    type: "PLAYING"
    # URL for streaming activity (only used when type is STREAMING)
    url: ""

  # Bot resource sources configuration
  sources:
    # Commands configuration
    commands:
      # Mode: local (load from bot folder) or global (load from global commands folder)
      mode: "local"
      # Local command files (relative to bot's command folder)
      local:
        - "commands.yml"
      # Global command files (relative to global commands folder)
      global:
        - "commands.yml"

    # Avatar configuration
    avatar:
      # Mode: local (load from bot folder) or global (load from global avatar folder)
      mode: "local"
      # Avatar file name
      file: "avatar-discordengine-nofon.png"

    # Language configuration
    lang:
      # Mode: local (load from bot folder) or global (load from global lang folder)
      mode: "local"
      # Language file name
      file: "en_US.yml"

# Bot-specific settings
settings:
  # Enable this bot
  enabled: true

  # Bot description
  description: "Default Discord Engine bot"

  # Auto-reconnect on connection loss
  auto_reconnect: true
  # Maximum reconnection attempts
  max_reconnect_attempts: 5

  # Reconnection delay in seconds
  reconnect_delay: 30

# Development and debugging settings
debug:
  # Enable debug logging for this bot
  enabled: false

  # Log all Discord API calls
  log_api_calls: false

  # Log command executions
  log_commands: true

  # Log bot events
  log_events: false