config: # Please do not touch this section
  version: 1
  type: config

bot:
  token: "your-bot-token"
  activity: "Discord Engine"
  avatar: "avatar-discordengine-nofon.png"

language: "en_US"
addonsHelp: true