name: DiscordEngine
version: 1.0.0
main: com.wairesdindustries.discordengine.paper.DEPaperBootstrap
api-version: 1.20
authors: [1wairesd]

libraries:
  - net.dv8tion:JDA:5.6.1
  - org.yaml:snakeyaml:2.2

commands:
  discordengine:
    description: DiscordEngine base command
    usage: /<command> help
    aliases: [de, dengine]